# Generated by Django 3.2.4 on 2021-06-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_alter_edificio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='costo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='num_cuartos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='ciudad',
            field=models.CharField(max_length=30),
        ),
    ]
